name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  dots_indicator: ^3.0.0
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^3.5.2
  font_awesome_flutter: ^10.8.0

  get: ^4.3.8
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
